CREATE TABLE EMPL(
EMP_ID INT,
NAME VARCHAR(100),
AGE INT
);

INSERT INTO empl
VALUES(1,"Rohit", 25), (2, "Sadhana", 23), (3, "Kedar", 28);

CREATE TABLE DEPTE(
Dept_ID INT,
Dept_Name VARCHAR(100),
Emp_ID INT
);

INSERT INTO DEPTE
VALUES(101, "HR", 3), (102, "Marketing", 1), (103, "Finance", 10);

SELECT*FROM EMPL
LEFT JOIN depte
USING(EMP_ID)
UNION
SELECT*FROM EMPL
RIGHT JOIN depte
USING(EMP_ID);