CREATE TABLE LAPTOP(
LAPTOP_NAME varchar(100)
);
insert INTO LAPTOP
values("HP"),("DELL"),("ASUS");

CREATE TABLE COLOUR(
COLOUR_NAME varchar(100)
);
INSERT INTO COLOUR
values("SILVER"),("BLACK"),("WHIGHT");

SELECT*FROM LAPTOP CROSS JOIN COLOUR;