CREATE VIEW CUSTOMERWISESTATUS AS
   SELECT C.CUSTOMERNUMBER,C.CUSTOMERNAME,COUNT(O.ORDERNUMBER) AS TOTAL_ORDERS
   FROM CUSTOMERS C INNER JOIN orders O
   USING (CUSTOMERNUMBER)
   GROUP BY C. CUSTOMERNUMBER
   ORDER BY TOTAL_ORDERS DESC;
   
   
   
SELECT*FROM CUSTOMERWISESTATUS;

ALTER VIEW CUSTOMERWISESTATUS AS
   SELECT C.CUSTOMERNUMBER,C.CUSTOMERNAME,COUNT(O.ORDERNUMBER) AS TOTAL_ORDERS,sum(OD. QUANTITYORDERED* OD. PRICEEACH) AS SALE 
   FROM CUSTOMERS C INNER JOIN orders O
   USING (CUSTOMERNUMBER)
   INNER JOIN orderdetails OD USING(ORDERNUMBER)
   GROUP BY C. CUSTOMERNUMBER
   ORDER BY TOTAL_ORDERS DESC;
   
   
   
DROP VIEW CUSTOMERWISESTATUS;

RENAME TABLE CUSTOMERWISESTATUS TO XYZ;
RENAME TABLE XYZ TO CUSTOMERWISESTATUS;