DELIMITER //
CREATE PROCEDURE GETSTATUS(IN PARAM_CUSTOMERNUM INT,OUT PARAM_STATUS VARCHAR(100))
BEGIN
	  DECLARE CREDIT_VARIABLE DECIMAL(10,2); 
      
      select CREDITLIMIT into CREDIT_VARIABLE
      FROM CUSTOMERS
      WHERE CUSTOMERNUMBER=PARAM_CUSTOMERNUM;
      
      IF CREDIT_VARIABLE>100000 THEN
      SET PARAM_STATUS="PLATINUM";
      
      ELSEIF CREDIT_VARIABLE  BETWEEN 50000 AND 100000 THEN 
      SET PARAM_STATUS="GOLD";
      
      ELSEIF CREDIT_VARIABLE<50000 THEN
       SET PARAM_STATUS="SILVER";
      
      END IF;
      
      
END//
 
 CALL GETSTATUS(114,@XYZ);
 SELECT @XYZ;