CREATE TABLE STUDENTS(
ROLL_NO INT NOT NULL,
NAME VARCHAR(100)DEFAULT"-",
AGE INT CHECK(AGE<17),
GENDER ENUM("M","F")
);



INSERT INTO STUDENTS
VALUE(NULL,"A",15,"M");

INSERT INTO STUDENTS
VALUE(1,NULL,15,"M");

INSERT INTO STUDENTS (ROLL_NO)
VALUE(2);

INSERT INTO STUDENTS
VALUE(3,"B",25,"M");

INSERT INTO STUDENTS
VALUE(4,"C",10,"S");